method: bayes   #Available options : [grid, random, bayes]
entity: adversarial_robustness 
project: bayes_VAE
metric:
    name: validation_auc
    goal: maximize

parameters: 
    #Describe parameters here
    learning_rate:
        {'max': 0.01, 'min': 0.00001}
    optimizer:
        values: ['Nadam']
    hidden_size:
        values: [8,16,32]
    batch_size:
        values:  [128,256] 
#no regularizers, cause too many variables then
early_terminate:
    type: hyperband
    min_iter: 1